# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://woood.co
title: Woood
email: hello@woood.co
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: '/blog/:title/'
paginate_path: '/blog/page:num/'

# Configure pages
include: ['_pages']
relative_permalinks: false

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Email us
    url: mailto:team@woood.co
    icon: envelope
  - title: facebook
    url: https://www.facebook.com/woooddesign
    icon: facebook
  - title: twitter
    url: https://twitter.com/woooddesign
    icon: twitter

navigation:
  - title: About
    url: /about
  - title: Products
    url: /products
  - title: Contact
    url: /contact

exclude: ['CNAME', 'LICENSE', 'README.md']

# Serving
detach:  false
port:    80
host:    0.0.0.0
baseurl: "" # does not include hostname
