# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://woood.co
title: Woood
email: hello@woood.co
description: >
    Woood is a team of young designers
    bringing you great wooden furniture manifactured in-house.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: '/blog/:title/'
paginate_path: '/blog/page:num/'

# Configure pages
include: ['_pages']
relative_permalinks: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # overrides previous default layout

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

exclude: ['CNAME', 'LICENSE', 'README.md']

# Serving
detach:  false
port:    80
host:    0.0.0.0
baseurl: "" # does not include hostname
